version: "3.8"

services:
  php:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    container_name: php
    command: php-fpm
    volumes:
      - .:/app
      - .docker/config/dev.ini:/usr/local/etc/php/php.ini
    depends_on:
      - gotenberg

  gotenberg:
    image: gotenberg/gotenberg:7
    container_name: gotenberg
    environment:
      GOTENBERG_DEFAULT_WAIT_TIMEOUT: 180s
    ports:
      - "3000:3000"
