version: "3.8"

services:
  php:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    container_name: php
    command: php-fpm
    volumes:
      - .:/app
    depends_on:
      - gotenberg

  gotenberg:
    image: gotenberg/gotenberg:7
    container_name: gotenberg
    ports:
      - "3000:3000"
